sudo: required
dist: trusty
language: python
python:
  - "2.7"
  - "3.5"
before_install:
install: pip install tox-travis
script: tox
deploy:
  provider: pypi
  user: biocommons
  password:
    secure: "use `travis encrypt --add deploy.password -r biocommons/<repo>`"
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: biocommons/seqrepo
    branch: master
